Document: ssh2com
Title: Debian ssh2com Manual
Author: <insert document author here>
Abstract: This manual describes what ssh2com is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ssh2com/ssh2com.sgml.gz

Format: postscript
Files: /usr/share/doc/ssh2com/ssh2com.ps.gz

Format: text
Files: /usr/share/doc/ssh2com/ssh2com.text.gz

Format: HTML
Index: /usr/share/doc/ssh2com/html/index.html
Files: /usr/share/doc/ssh2com/html/*.html
